osneal/mascotas/urls.py
from django.urls import path,re_path
from django.views.generic import TemplateView
from .views import (
    CrearMascota,
    BorrarMascota,
    ModificarMascota,
    BuscarMascota,
    CrearHistorial,
    EditarHistorialView,
    ListarHistorialesView,
    BorrarHistorialVew,
    CrearVacunaView,
    MascotasAutocomplete,
    MascotasByDniAutocomplete,
    ListarVacunasView,
    EditarVacunaView,
    BorrarVacunaView,

    #Vistas para usuarios propietarios
    MisMascotasView,
    VacunasMisMascotasView,
    HistorialesMisMascotasView,

    )

app_name = 'mascotas'

urlpatterns = [
    # MASCOTAS ADMIN
    path('carga/', CrearMascota.as_view(),name='carga'),
    path('<int:pk>/borrar/', BorrarMascota.as_view(),name='borrar'),
    path('<int:pk>/modificar/', ModificarMascota.as_view(),name='modificar'),
    path('buscar/', BuscarMascota.as_view(),name='buscar'),

    # HISTORIALES ADMIN
    path('carga_historial/', CrearHistorial.as_view(),name='carga_historial'),
    path('<int:pk>/editar_historial/', EditarHistorialView.as_view(),name='editar_historial'),
    path('<int:pk>/listado_historiales/', ListarHistorialesView.as_view(),name='listado_historiales'),
    path('<int:pk>/borrar_historial/', BorrarHistorialVew.as_view(),name='borrar_historial'),

    # VACUNAS ADMIN
    path('carga_vacuna/', CrearVacunaView.as_view(),name='carga_vacuna'),
    path('<int:pk>/listado_vacunas/', ListarVacunasView.as_view(),name='listado_vacunas'),
    path('<int:pk>/editar_vacuna/', EditarVacunaView.as_view(),name='editar_vacuna'),
    path('<int:pk>/borrar_vacuna/', BorrarVacunaView.as_view(),name='borrar_vacuna'),

    #URLS PARA USUARIOS COMUNES
    path('mis_mascotas/',MisMascotasView.as_view(),name='mis_mascotas'),
    path('mis_mascotas/<int:pk>/vacunas',VacunasMisMascotasView.as_view(),name='mis_mascotas_vacunas'),
    path('mis_mascotas/<int:pk>/historial',HistorialesMisMascotasView.as_view(),name='mis_mascotas_historial'),

    # AUTOCOMPLETE
    re_path(
        r'^mascotas-autocomplete/$',
        MascotasAutocomplete.as_view(),
        name='mascotas-autocomplete',
    ),
    re_path(
        r'^mascotas-by-dni-autocomplete/$',
        MascotasByDniAutocomplete.as_view(),
        name='mascotas-by-dni-autocomplete',
    ),

    ]

osneal/turnos/urls.py
from django.urls import path
from django.views.generic import TemplateView
from .views import (
    crear_turno,
    obtener_turnos,
    borrar_turno,
    )


app_name='turnos'

urlpatterns = [
    path('turnos_admin/', TemplateView.as_view(template_name='turnos/admin/turnos_admin.html'),name='turnos_admin'),
    path('crear_turnos_admin/', crear_turno,name='crear_turnos_admin'),
    path('obtener_turnos_admin/', obtener_turnos,name='obtener_turnos_admin'),
    path('borrar_turnos_admin/', borrar_turno,name='borrar_turnos_admin'),
    path('turnos_usuario/', TemplateView.as_view(template_name='vista_usuarios/turnos_usuario.html'),name='turnos_usuario'),
]

osneal/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('mascotas/', include('mascotas.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATICFILES_DIRS[0])

osneal/usuarios/urls.py
from django.urls import path,re_path
from django.views.generic import TemplateView
from .views import (
    UserLoginView,
    UserLogoutView,
    CrearUsuarioView,
    json_buscar_usuario,
    BuscarUsuarioView,
    EditarUsuarioView,
    BorrarUsuarioView,
    UsuarioAutocomplete,
    )


app_name='usuarios'

urlpatterns = [
    # path('crear_usuario/', crear_usario,name='crear_usuario'),
    path('login/', UserLoginView.as_view(),name='login'),
    path('logout/', UserLogoutView.as_view(),name='logout'),
    path('crear_usuario/', CrearUsuarioView.as_view(),name='crear_usuario'),
    path('json_buscar_usuario/<dni>', json_buscar_usuario,name='json_buscar_usuario'),
    path('buscar_usuario/', BuscarUsuarioView.as_view(),name='buscar_usuario'),
    path('<int:pk>/editar_usuario/', EditarUsuarioView.as_view(),name='editar_usuario'),
    path('<int:pk>/borrar_usuario/', BorrarUsuarioView.as_view(),name='borrar_usuario'),
    re_path(
        r'^usuario-autocomplete/$',
        UsuarioAutocomplete.as_view(),
        name='usuario-autocomplete',
    ),

]

users/urls.py
from django.contrib import admin
from django.urls import path
from .views import InicarSesion,CerrarSesion

app_name = 'users'

urlpatterns = [
    path('iniciar-sesion/',InicarSesion.as_view(),name='iniciar-sesion'),
    path('salir/',CerrarSesion.as_view(),name='salir'),
]

osneal/pagos/models.py
from django.db import models

# Create your models here.

osneal/mascotas/views.py
from django.shortcuts import render,redirect
from django.views.generic import CreateView, DeleteView, UpdateView, ListView
from mascotas.forms import MascotaForm,HistorialForm,VacunaForm, EditarHistorialForm,EditarVacunaForm
from mascotas.models import Mascota,Vacuna,HistorialClinico
from usuarios.models import Usuario
from mascotas.tables import VacunaTable, HistorialTable,VacunaTablePropietario,HistorialTablePropietario
from django.urls import reverse_lazy
from dal import autocomplete
from django_tables2 import SingleTableView
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.contrib import messages




# MASCOTAS
class CrearMascota(PermissionRequiredMixin,SuccessMessageMixin,CreateView):
    '''Clase para crear mascotas'''
    template_name = 'mascotas/carga_admin.html'
    success_url = reverse_lazy('mascotas:carga')
    form_class = MascotaForm
    success_url = reverse_lazy('mascotas:carga')
    success_message = "Mascota creada correctamente"
    permission_required = 'mascotas.add_mascota'
    login_url = reverse_lazy('usuarios:login')




class BorrarMascota(PermissionRequiredMixin,DeleteView):
    queryset = Mascota.objects.all()
    success_url = reverse_lazy('mascotas:carga')
    template_name = 'mascotas/carga_admin.html'
    pk_url_kwarg = 'pk'
    permission_required = 'mascotas.delete_mascota'
    login_url = reverse_lazy('usuarios:login')
    success_message = "Mascota eliminada correctamente"


    def get(self, request, *args, **kwargs):
        self.delete(self, request, *args, **kwargs)
        messages.success(self.request, self.success_message)
        return redirect('mascotas:carga')


class ModificarMascota(PermissionRequiredMixin,SuccessMessageMixin,UpdateView):
    '''Clase para modificar mascotas'''
    model = Mascota
    template_name = 'mascotas/modificar.html'
    form_class = MascotaForm
    pk_url_kwarg = 'pk'
    permission_required = 'mascotas.change_mascota'
    login_url = reverse_lazy('usuarios:login')
    success_url = reverse_lazy('mascotas:carga')
    success_message = "Mascota modificada correctamente"



class BuscarMascota(PermissionRequiredMixin,ListView):
    '''Clase para buscar mascotas'''
    model = Mascota
    template_name = 'mascotas/resultado_busqueda_mascotas.html'
    context_object_name = 'mascotas'
    permission_required = 'mascotas.view_mascota'
    login_url = reverse_lazy('usuarios:login')


    def get_queryset(self):
        '''Metodo para buscar mascotas'''
        queryset = super().get_queryset()
        busqueda = self.request.GET.get('mirco_chip',None)
        if busqueda:
            return queryset.filter(micro_chip__contains=busqueda)
        else:
            return queryset



class MascotasAutocomplete(PermissionRequiredMixin,autocomplete.Select2QuerySetView):
    '''Clase para autocompletar mascotas'''
    permission_required = 'mascotas.add_mascota'
    login_url = reverse_lazy('usuarios:login')

    def get_queryset(self):
        if not self.request.user.is_authenticated:
            return Mascota.objects.none()

        qs = Mascota.objects.all()

        if self.q:
            qs = qs.filter(micro_chip__istartswith=self.q)

        return qs


class MascotasByDniAutocomplete(PermissionRequiredMixin,autocomplete.Select2QuerySetView):
    '''Clase para autocompletar mascotas por dni'''
    permission_required = 'mascotas.add_mascota'
    login_url = reverse_lazy('usuarios:login')

    def get_queryset(self):
        if not self.request.user.is_authenticated:
            return Mascota.objects.none()

        qs = Mascota.objects.all()

        if self.q:
            qs = qs.filter(duenio__dni=self.q)

        return qs

# HISTORIAL

class CrearHistorial(PermissionRequiredMixin,SuccessMessageMixin,CreateView):
    '''Clase para crear historiales'''
    template_name = 'mascotas/historial_medico_admin.html'
    success_url = reverse_lazy('mascotas:carga_historial')
    form_class = HistorialForm
    permission_required = 'mascotas.add_historialclinico'
    login_url = reverse_lazy('usuarios:login')
    success_message = "Historial creado correctamente"

class BorrarHistorialVew(PermissionRequiredMixin,SuccessMessageMixin,DeleteView):
    '''Clase para eliminar historiales'''
    model = HistorialClinico
    pk_url_kwarg = 'pk'
    success_url = reverse_lazy('mascotas:buscar')
    success_message = "Historial eliminado correctamente"
    template_name = 'mascotas/carga_admin.html'
    permission_required = 'mascotas.delete_historialclinico'
    login_url = reverse_lazy('usuarios:login')

    def get(self, request, *args, **kwargs):
        self.delete(self, request, *args, **kwargs)
        messages.success(self.request, self.success_message)
        return redirect('mascotas:carga')


class EditarHistorialView(PermissionRequiredMixin,SuccessMessageMixin,UpdateView):
    '''Clase para modificar historiales'''
    model = HistorialClinico
    template_name = 'mascotas/historial_medico_admin.html'
    form_class = EditarHistorialForm
    pk_url_kwarg = 'pk'
    success_message = "Historial modificado correctamente"
    permission_required = 'mascotas.change_historialclinico'
    login_url = reverse_lazy('usuarios:login')
    success_url = reverse_lazy('mascotas:carga')

class ListarHistorialesView(PermissionRequiredMixin,SingleTableView):
    '''Clase para listar historiales de una mascota'''
    model = HistorialClinico
    template_name = 'mascotas/listado_historiales.html'
    table_class = HistorialTable
    permission_required = 'mascotas.change_historialclinico'
    login_url = reverse_lazy('usuarios:login')

    def get_queryset(self):
        '''Metodo para buscar mascotas'''
        queryset = super().get_queryset()
        busqueda = self.kwargs.get('pk',None)
        if busqueda:
            return queryset.filter(mascota__id=busqueda)
        else:
            return queryset



# VACUNAS
class CrearVacunaView(PermissionRequiredMixin,SuccessMessageMixin,CreateView):
    '''Clase para crear vacunas'''
    template_name = 'mascotas/vacunas_admin.html'
    success_url = reverse_lazy('mascotas:carga')
    form_class = VacunaForm
    permission_required = 'mascotas.add_vacuna'
    login_url = reverse_lazy('usuarios:login')
    success_message = "Vacuna cargada correctamente"

class ListarVacunasView(PermissionRequiredMixin,SingleTableView):
    '''Clase para listar vacunas de una mascota'''
    model = Vacuna
    template_name = 'mascotas/listado_vacunas.html'
    context_object_name = 'vacunas'
    table_class = VacunaTable
    permission_required = 'mascotas.view_vacuna'
    login_url = reverse_lazy('usuarios:login')

    def get_queryset(self):
        '''Metodo para buscar mascotas'''
        queryset = super().get_queryset()
        busqueda = self.kwargs.get('pk')
        print(busqueda)
        if busqueda:
            return queryset.filter(mascota=busqueda)
        else:
            return queryset


class EditarVacunaView(PermissionRequiredMixin,SuccessMessageMixin,UpdateView):
    '''Clase para listar vacunas de una mascota'''
    model = Vacuna
    template_name = 'mascotas/vacunas_admin.html'
    form_class = EditarVacunaForm
    pk_url_kwarg = 'pk'
    permission_required = 'mascotas.change_vacuna'
    login_url = reverse_lazy('usuarios:login')
    success_url = reverse_lazy('mascotas:carga')
    success_message = "Vacuna modificada correctamente"


class BorrarVacunaView(PermissionRequiredMixin,SuccessMessageMixin,DeleteView):
    '''Clase para eliminar vacunas de una mascota'''
    model = Vacuna
    pk_url_kwarg = 'pk'
    success_message = "Vacuna eliminada correctamente"
    success_url = reverse_lazy('mascotas:carga')
    template_name = 'mascotas/vacunas_admin.html'
    permission_required = 'mascotas.delete_mascota'
    login_url = reverse_lazy('usuarios:login')

    def get(self, request, *args, **kwargs):
        self.delete(self, request, *args, **kwargs)
        messages.success(self.request, self.success_message)
        return redirect('mascotas:carga')


class MisMascotasView(PermissionRequiredMixin,ListView):
    '''Clase para listar las mascotas de un usuario'''
    model = Mascota
    template_name = 'vista_usuarios/mascotas_usuario.html'
    context_object_name = 'mascotas'
    permission_required = 'mascotas.view_mascota'
    login_url = reverse_lazy('usuarios:login')

    def get_queryset(self):
        '''Metodo para buscar mascotas'''
        queryset = super().get_queryset()
        busqueda = self.request.user
        if busqueda:
            return queryset.filter(duenio=busqueda)
        else:
            return queryset

class VacunasMisMascotasView(PermissionRequiredMixin,SingleTableView):
    '''Clase para listar las vacunas de las mascotas de un usuario'''
    model = Vacuna
    template_name = 'vista_usuarios/listado_vacunas.html'
    context_object_name = 'vacunas'
    permission_required = 'mascotas.view_vacuna'
    login_url = reverse_lazy('usuarios:login')
    table_class = VacunaTablePropietario

    def get_queryset(self):
        pk = self.kwargs.get('pk')
        queryset = super().get_queryset()
        queryset = queryset.filter(mascota__duenio=self.request.user).filter(mascota__id=pk)

        return queryset


class HistorialesMisMascotasView(PermissionRequiredMixin,SingleTableView):
    '''Clase para listar los historiales de las mascotas de un usuario'''
    model = HistorialClinico
    template_name = 'vista_usuarios/historial_usuario.html'
    permission_required = 'mascotas.view_historialclinico'
    login_url = reverse_lazy('usuarios:login')
    table_class = HistorialTablePropietario

    def get_queryset(self,**kwargs):
        queryset = super().get_queryset()
        queryset = queryset.filter(mascota__duenio=self.request.user).filter(mascota__id=self.kwargs.get('pk'))
        return queryset

osneal/pagos/views.py
from django.shortcuts import render

# Create your views here.

osneal/turnos/views.py
from django.shortcuts import render
from django.http import JsonResponse
from .models import Turno
from .forms import TurnoForm
from mascotas.models import Mascota
from django.contrib.auth.decorators import login_required, permission_required

@login_required
@permission_required('turnos.add_turno',raise_exception=True)
def crear_turno(request):
    if request.method == 'POST':

        mascota = request.POST.get('mascota')

        if not mascota.find(" - ") == -1:
            microchip = mascota.split(" - ")[0]
        elif mascota.isnumeric():
            microchip = mascota
        else:
            return JsonResponse({"mensaje" : {"Error":"El número de microchip no existe"}},status=400)

        mascota = Mascota.objects.filter(micro_chip=microchip).first()

        if not mascota:
            return JsonResponse({"mensaje" : {"Error":"El número de microchip no existe"}},status=400)

        request.POST._mutable = True
        request.POST['mascota'] = mascota.pk
        form = TurnoForm(request.POST, initial={'mascota': mascota})

        if not form.is_valid():
            return JsonResponse({"mensaje" : form.errors},status=400)

        form.save()

        return JsonResponse({},status=201)
    else:
        return JsonResponse({"mensaje":"Este método no está permitido"},status=403)


@login_required
@permission_required('turnos.view_turno',raise_exception=True)
def obtener_turnos(request):
    if request.method == 'GET':
        turnos = Turno.objects.all()
        print(request.user.tipo_usuario)
        if request.user.tipo_usuario == 'propietario':
            turnos = turnos.filter(mascota__duenio=request.user)
        turnos_json = []
        for turno in turnos:
            turnos_json.append({
                'id': turno.pk,
                'mascota': turno.mascota.nombre,
                'title': turno.descripcion_corta,
                'descripcion': turno.descripcion,
                'tipo_turno': turno.tipo_turno,
                'start': turno.inicio.strftime("%Y-%m-%dT%H:%M:%S"),
                'end': turno.fin.strftime("%Y-%m-%dT%H:%M:%S")
            })
        return JsonResponse(turnos_json,status=200,safe=False)
    else:
        return JsonResponse({"mensaje":"Este método no está permitido"},status=403)


@login_required
@permission_required('turnos.delete_turno',raise_exception=True)
def borrar_turno(request):
    if request.method == 'POST':
        id_turno = request.POST.get('id_turno')
        print(id_turno)
        turno = Turno.objects.filter(pk=id_turno).first()
        if turno:
            turno.delete()
            return JsonResponse({},status=200)
        else:
            return JsonResponse({"mensaje" : {"Error":"El turno no existe"}},status=400)
    else:
        return JsonResponse({"mensaje":"Este método no está permitido"},status=403)

osneal/templates/dash-base.html
{% load static %}
<!DOCTYPE html>
<html lang="en" dir="ltr">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">

  {% block titulo %}

  <title> OSNeAl - Panel </title>
  {% endblock titulo %}

  <link rel="stylesheet" href="{% static 'css/dash-base.css' %}">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
    integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous" />
  <!-- Boxicons CDN Link -->
  <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <!-- jquery -->
  <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.0/jquery.min.js"></script>


  <!-- jBox -->
  <script src="https://cdn.jsdelivr.net/gh/StephanWagner/jBox@v1.3.3/dist/jBox.all.min.js"></script>
  <link href="https://cdn.jsdelivr.net/gh/StephanWagner/jBox@v1.3.3/dist/jBox.all.min.css" rel="stylesheet">


  {% block encabezado %}

  {% endblock encabezado %}
</head>


<body>

  <!-- COMIENZA PANEL -->
  <div class="sidebar">
    <div class="logo_content">
      <div class="logo">
        <div class="logo_name">Panel de Administración</div>
      </div>
      <i class='bx bx-menu' id="btn"></i>
    </div>

    <ul class="nav_list">

      {% if user.tipo_usuario != 'propietario' %}
      <li>
        <a href="{% url 'usuarios:crear_usuario' %}">
          <i class='bx bxs-user-plus'></i>
          <span class="links_name">Propietarios</span>
        </a>
        <span class="tooltip">Propietarios</span>
      </li>
      {% endif %}

      <li>
        {% if user.tipo_usuario == 'propietario' %}
        <a href="{% url 'mascotas:mis_mascotas' %}">
          {% else %}
          <a href="{% url 'mascotas:carga' %}">
          {% endif %}
            <i class='bx bxs-cat'></i>
            <span class="links_name">Mascotas</span>
          </a>
          <span class="tooltip">Mascotas</span>
      </li>


      {% if user.tipo_usuario == 'Administrador' or user.is_admin %}
      <li>
        <a href="{% url 'turnos:turnos_admin' %}">
          <i class='bx bxs-calendar-edit'></i>
          <span class="links_name">Turnos</span>
        </a>
        <span class="tooltip">Turnos</span>
      </li>
      {% else %}
      <li>
        <a href="{% url 'turnos:turnos_usuario' %}">
          <i class='bx bxs-calendar-edit'></i>
          <span class="links_name">Turnos</span>
        </a>
        <span class="tooltip">Turnos</span>
      </li>

      {% endif %}


      {% if user.tipo_usuario != 'propietario' %}
      <li>
        <a href="{% url 'mascotas:carga_historial' %}">

          <i class='bx bxs-id-card'></i>
          <span class="links_name">Historial Clinico</span>
        </a>
        <span class="tooltip">Historial</span>
      </li>

      <li>
        <a href="{% url 'mascotas:carga_vacuna' %}">
          <i class='bx bxs-injection'></i>
          <span class="links_name">Vacunas</span>
        </a>
        <span class="tooltip">Vacunas</span>
      </li>
      {% endif %}
      <!-- TERMINA LISTA DE OPCIONES DEL PANEL -->
      <!-- Footer del panel -->
    </ul>
    <div class="content">
      <div class="user">
        <div class="user_details">
          <div class="name_job">
            {% if user.is_authenticated %}
            <div class="name">{{user.email}}</div>
            {% if user.tipo_usuario.value == 'Administrador' or user.is_admin %}
            <div class="job">Administrador</div>
            {% elif user.tipo_usuario.value == 'Veterinario' %}
            <div class="job">Veterinario</div>
            {% else %}
            <div class="job">Propietario</div>
            {% endif %}
            {% else %}
            <div class="name">Nombre Usuario</div>
            <div class="job">Tipo Usuario</div>
            {% endif %}
          </div>
        </div>
        <a href="{% url 'usuarios:logout' %}">

          <i class='bx bx-log-out' id="log_out"></i>
        </a>
      </div>
    </div>
  </div>
  <div class="home_content">
    <!-- Termina el Footer del panel -->


    <!-- COMIENZA CONTENIDO DEL MENU -->

    {% block contenido %}

    {% endblock contenido %}


  </div>
  </div>



  <script src="{% static 'js/dash-base.js' %}"></script>
  <!-- <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script> -->
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>


  {% block js %}

  {% endblock js %}
</body>

</html>