osneal/mascotas/urls.py
from django.urls import path,re_path
from django.views.generic import TemplateView
from .views import (
    CrearMascota,
    BorrarMascota,
    ModificarMascota,
    BuscarMascota,
    CrearHistorial,
    EditarHistorialView,
    ListarHistorialesView,
    BorrarHistorialVew,
    CrearVacunaView,
    MascotasAutocomplete,
    MascotasByDniAutocomplete,
    ListarVacunasView,
    EditarVacunaView,
    BorrarVacunaView,

    #Vistas para usuarios propietarios
    MisMascotasView,
    VacunasMisMascotasView,
    HistorialesMisMascotasView,

    )

app_name = 'mascotas'

urlpatterns = [
    # MASCOTAS ADMIN
    path('carga/', CrearMascota.as_view(),name='carga'),
    path('<int:pk>/borrar/', BorrarMascota.as_view(),name='borrar'),
    path('<int:pk>/modificar/', ModificarMascota.as_view(),name='modificar'),
    path('buscar/', BuscarMascota.as_view(),name='buscar'),

    # HISTORIALES ADMIN
    path('carga_historial/', CrearHistorial.as_view(),name='carga_historial'),
    path('<int:pk>/editar_historial/', EditarHistorialView.as_view(),name='editar_historial'),
    path('<int:pk>/listado_historiales/', ListarHistorialesView.as_view(),name='listado_historiales'),
    path('<int:pk>/borrar_historial/', BorrarHistorialVew.as_view(),name='borrar_historial'),

    # VACUNAS ADMIN
    path('carga_vacuna/', CrearVacunaView.as_view(),name='carga_vacuna'),
    path('<int:pk>/listado_vacunas/', ListarVacunasView.as_view(),name='listado_vacunas'),
    path('<int:pk>/editar_vacuna/', EditarVacunaView.as_view(),name='editar_vacuna'),
    path('<int:pk>/borrar_vacuna/', BorrarVacunaView.as_view(),name='borrar_vacuna'),

    #URLS PARA USUARIOS COMUNES
    path('mis_mascotas/',MisMascotasView.as_view(),name='mis_mascotas'),
    path('mis_mascotas/<int:pk>/vacunas',VacunasMisMascotasView.as_view(),name='mis_mascotas_vacunas'),
    path('mis_mascotas/<int:pk>/historial',HistorialesMisMascotasView.as_view(),name='mis_mascotas_historial'),

    # AUTOCOMPLETE
    re_path(
        r'^mascotas-autocomplete/$',
        MascotasAutocomplete.as_view(),
        name='mascotas-autocomplete',
    ),
    re_path(
        r'^mascotas-by-dni-autocomplete/$',
        MascotasByDniAutocomplete.as_view(),
        name='mascotas-by-dni-autocomplete',
    ),

    ]

osneal/turnos/urls.py
from django.urls import path
from django.views.generic import TemplateView
from .views import (
    crear_turno,
    obtener_turnos,
    borrar_turno,
    )


app_name='turnos'

urlpatterns = [
    path('turnos_admin/', TemplateView.as_view(template_name='turnos/admin/turnos_admin.html'),name='turnos_admin'),
    path('crear_turnos_admin/', crear_turno,name='crear_turnos_admin'),
    path('obtener_turnos_admin/', obtener_turnos,name='obtener_turnos_admin'),
    path('borrar_turnos_admin/', borrar_turno,name='borrar_turnos_admin'),
    path('turnos_usuario/', TemplateView.as_view(template_name='vista_usuarios/turnos_usuario.html'),name='turnos_usuario'),
]

osneal/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('mascotas/', include('mascotas.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATICFILES_DIRS[0])

osneal/usuarios/urls.py
from django.urls import path,re_path
from django.views.generic import TemplateView
from .views import (
    UserLoginView,
    UserLogoutView,
    CrearUsuarioView,
    json_buscar_usuario,
    BuscarUsuarioView,
    EditarUsuarioView,
    BorrarUsuarioView,
    UsuarioAutocomplete,
    )


app_name='usuarios'

urlpatterns = [
    # path('crear_usuario/', crear_usario,name='crear_usuario'),
    path('login/', UserLoginView.as_view(),name='login'),
    path('logout/', UserLogoutView.as_view(),name='logout'),
    path('crear_usuario/', CrearUsuarioView.as_view(),name='crear_usuario'),
    path('json_buscar_usuario/<dni>', json_buscar_usuario,name='json_buscar_usuario'),
    path('buscar_usuario/', BuscarUsuarioView.as_view(),name='buscar_usuario'),
    path('<int:pk>/editar_usuario/', EditarUsuarioView.as_view(),name='editar_usuario'),
    path('<int:pk>/borrar_usuario/', BorrarUsuarioView.as_view(),name='borrar_usuario'),
    re_path(
        r'^usuario-autocomplete/$',
        UsuarioAutocomplete.as_view(),
        name='usuario-autocomplete',
    ),

]

users/urls.py
from django.contrib import admin
from django.urls import path
from .views import InicarSesion,CerrarSesion

app_name = 'users'

urlpatterns = [
    path('iniciar-sesion/',InicarSesion.as_view(),name='iniciar-sesion'),
    path('salir/',CerrarSesion.as_view(),name='salir'),
]

osneal/pagos/models.py
from django.db import models

# Create your models here.

osneal/mascotas/views.py
from django.shortcuts import render,redirect
from django.views.generic import CreateView, DeleteView, UpdateView, ListView
from mascotas.forms import MascotaForm,HistorialForm,VacunaForm, EditarHistorialForm,EditarVacunaForm
from mascotas.models import Mascota,Vacuna,HistorialClinico
from usuarios.models import Usuario
from mascotas.tables import VacunaTable, HistorialTable,VacunaTablePropietario,HistorialTablePropietario
from django.urls import reverse_lazy
from dal import autocomplete
from django_tables2 import SingleTableView
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.contrib import messages




# MASCOTAS
class CrearMascota(PermissionRequiredMixin,SuccessMessageMixin,CreateView):
    '''Clase para crear mascotas'''
    template_name = 'mascotas/carga_admin.html'
    success_url = reverse_lazy('mascotas:carga')
    form_class = MascotaForm
    success_url = reverse_lazy('mascotas:carga')
    success_message = "Mascota creada correctamente"
    permission_required = 'mascotas.add_mascota'
    login_url = reverse_lazy('usuarios:login')




class BorrarMascota(PermissionRequiredMixin,DeleteView):
    queryset = Mascota.objects.all()
    success_url = reverse_lazy('mascotas:carga')
    template_name = 'mascotas/carga_admin.html'
    pk_url_kwarg = 'pk'
    permission_required = 'mascotas.delete_mascota'
    login_url = reverse_lazy('usuarios:login')
    success_message = "Mascota eliminada correctamente"


    def get(self, request, *args, **kwargs):
        self.delete(self, request, *args, **kwargs)
        messages.success(self.request, self.success_message)
        return redirect('mascotas:carga')


class ModificarMascota(PermissionRequiredMixin,SuccessMessageMixin,UpdateView):
    '''Clase para modificar mascotas'''
    model = Mascota
    template_name = 'mascotas/modificar.html'
    form_class = MascotaForm
    pk_url_kwarg = 'pk'
    permission_required = 'mascotas.change_mascota'
    login_url = reverse_lazy('usuarios:login')
    success_url = reverse_lazy('mascotas:carga')
    success_message = "Mascota modificada correctamente"



class BuscarMascota(PermissionRequiredMixin,ListView):
    '''Clase para buscar mascotas'''
    model = Mascota
    template_name = 'mascotas/resultado_busqueda_mascotas.html'
    context_object_name = 'mascotas'
    permission_required = 'mascotas.view_mascota'
    login_url = reverse_lazy('usuarios:login')


    def get_queryset(self):
        '''Metodo para buscar mascotas'''
        queryset = super().get_queryset()
        busqueda = self.request.GET.get('mirco_chip',None)
        if busqueda:
            return queryset.filter(micro_chip__contains=busqueda)
        else:
            return queryset



class MascotasAutocomplete(PermissionRequiredMixin,autocomplete.Select2QuerySetView):
    '''Clase para autocompletar mascotas'''
    permission_required = 'mascotas.add_mascota'
    login_url = reverse_lazy('usuarios:login')

    def get_queryset(self):
        if not self.request.user.is_authenticated:
            return Mascota.objects.none()

        qs = Mascota.objects.all()

        if self.q:
            qs = qs.filter(micro_chip__istartswith=self.q)

        return qs


class MascotasByDniAutocomplete(PermissionRequiredMixin,autocomplete.Select2QuerySetView):
    '''Clase para autocompletar mascotas por dni'''
    permission_required = 'mascotas.add_mascota'
    login_url = reverse_lazy('usuarios:login')

    def get_queryset(self):
        if not self.request.user.is_authenticated:
            return Mascota.objects.none()

        qs = Mascota.objects.all()

        if self.q:
            qs = qs.filter(duenio__dni=self.q)

        return qs

# HISTORIAL

class CrearHistorial(PermissionRequiredMixin,SuccessMessageMixin,CreateView):
    '''Clase para crear historiales'''
    template_name = 'mascotas/historial_medico_admin.html'
    success_url = reverse_lazy('mascotas:carga_historial')
    form_class = HistorialForm
    permission_required = 'mascotas.add_historialclinico'
    login_url = reverse_lazy('usuarios:login')
    success_message = "Historial creado correctamente"

class BorrarHistorialVew(PermissionRequiredMixin,SuccessMessageMixin,DeleteView):
    '''Clase para eliminar historiales'''
    model = HistorialClinico
    pk_url_kwarg = 'pk'
    success_url = reverse_lazy('mascotas:buscar')
    success_message = "Historial eliminado correctamente"
    template_name = 'mascotas/carga_admin.html'
    permission_required = 'mascotas.delete_historialclinico'
    login_url = reverse_lazy('usuarios:login')

    def get(self, request, *args, **kwargs):
        self.delete(self, request, *args, **kwargs)
        messages.success(self.request, self.success_message)
        return redirect('mascotas:carga')


class EditarHistorialView(PermissionRequiredMixin,SuccessMessageMixin,UpdateView):
    '''Clase para modificar historiales'''
    model = HistorialClinico
    template_name = 'mascotas/historial_medico_admin.html'
    form_class = EditarHistorialForm
    pk_url_kwarg = 'pk'
    success_message = "Historial modificado correctamente"
    permission_required = 'mascotas.change_historialclinico'
    login_url = reverse_lazy('usuarios:login')
    success_url = reverse_lazy('mascotas:carga')

class ListarHistorialesView(PermissionRequiredMixin,SingleTableView):
    '''Clase para listar historiales de una mascota'''
    model = HistorialClinico
    template_name = 'mascotas/listado_historiales.html'
    table_class = HistorialTable
    permission_required = 'mascotas.change_historialclinico'
    login_url = reverse_lazy('usuarios:login')

    def get_queryset(self):
        '''Metodo para buscar mascotas'''
        queryset = super().get_queryset()
        busqueda = self.kwargs.get('pk',None)
        if busqueda:
            return queryset.filter(mascota__id=busqueda)
        else:
            return queryset



# VACUNAS
class CrearVacunaView(PermissionRequiredMixin,SuccessMessageMixin,CreateView):
    '''Clase para crear vacunas'''
    template_name = 'mascotas/vacunas_admin.html'
    success_url = reverse_lazy('mascotas:carga')
    form_class = VacunaForm
    permission_required = 'mascotas.add_vacuna'
    login_url = reverse_lazy('usuarios:login')
    success_message = "Vacuna cargada correctamente"

class ListarVacunasView(PermissionRequiredMixin,SingleTableView):
    '''Clase para listar vacunas de una mascota'''
    model = Vacuna
    template_name = 'mascotas/listado_vacunas.html'
    context_object_name = 'vacunas'
    table_class = VacunaTable
    permission_required = 'mascotas.view_vacuna'
    login_url = reverse_lazy('usuarios:login')

    def get_queryset(self):
        '''Metodo para buscar mascotas'''
        queryset = super().get_queryset()
        busqueda = self.kwargs.get('pk')
        print(busqueda)
        if busqueda:
            return queryset.filter(mascota=busqueda)
        else:
            return queryset


class EditarVacunaView(PermissionRequiredMixin,SuccessMessageMixin,UpdateView):
    '''Clase para listar vacunas de una mascota'''
    model = Vacuna
    template_name = 'mascotas/vacunas_admin.html'
    form_class = EditarVacunaForm
    pk_url_kwarg = 'pk'
    permission_required = 'mascotas.change_vacuna'
    login_url = reverse_lazy('usuarios:login')
    success_url = reverse_lazy('mascotas:carga')
    success_message = "Vacuna modificada correctamente"


class BorrarVacunaView(PermissionRequiredMixin,SuccessMessageMixin,DeleteView):
    '''Clase para eliminar vacunas de una mascota'''
    model = Vacuna
    pk_url_kwarg = 'pk'
    success_message = "Vacuna eliminada correctamente"
    success_url = reverse_lazy('mascotas:carga')
    template_name = 'mascotas/vacunas_admin.html'
    permission_required = 'mascotas.delete_mascota'
    login_url = reverse_lazy('usuarios:login')

    def get(self, request, *args, **kwargs):
        self.delete(self, request, *args, **kwargs)
        messages.success(self.request, self.success_message)
        return redirect('mascotas:carga')


class MisMascotasView(PermissionRequiredMixin,ListView):
    '''Clase para listar las mascotas de un usuario'''
    model = Mascota
    template_name = 'vista_usuarios/mascotas_usuario.html'
    context_object_name = 'mascotas'
    permission_required = 'mascotas.view_mascota'
    login_url = reverse_lazy('usuarios:login')

    def get_queryset(self):
        '''Metodo para buscar mascotas'''
        queryset = super().get_queryset()
        busqueda = self.request.user
        if busqueda:
            return queryset.filter(duenio=busqueda)
        else:
            return queryset

class VacunasMisMascotasView(PermissionRequiredMixin,SingleTableView):
    '''Clase para listar las vacunas de las mascotas de un usuario'''
    model = Vacuna
    template_name = 'vista_usuarios/listado_vacunas.html'
    context_object_name = 'vacunas'
    permission_required = 'mascotas.view_vacuna'
    login_url = reverse_lazy('usuarios:login')
    table_class = VacunaTablePropietario

    def get_queryset(self):
        pk = self.kwargs.get('pk')
        queryset = super().get_queryset()
        queryset = queryset.filter(mascota__duenio=self.request.user).filter(mascota__id=pk)

        return queryset


class HistorialesMisMascotasView(PermissionRequiredMixin,SingleTableView):
    '''Clase para listar los historiales de las mascotas de un usuario'''
    model = HistorialClinico
    template_name = 'vista_usuarios/historial_usuario.html'
    permission_required = 'mascotas.view_historialclinico'
    login_url = reverse_lazy('usuarios:login')
    table_class = HistorialTablePropietario

    def get_queryset(self,**kwargs):
        queryset = super().get_queryset()
        queryset = queryset.filter(mascota__duenio=self.request.user).filter(mascota__id=self.kwargs.get('pk'))
        return queryset

osneal/pagos/views.py
from django.shortcuts import render

# Create your views here.

osneal/turnos/views.py
from django.shortcuts import render
from django.http import JsonResponse
from .models import Turno
from .forms import TurnoForm
from mascotas.models import Mascota
from django.contrib.auth.decorators import login_required, permission_required

@login_required
@permission_required('turnos.add_turno',raise_exception=True)
def crear_turno(request):
    if request.method == 'POST':

        mascota = request.POST.get('mascota')

        if not mascota.find(" - ") == -1:
            microchip = mascota.split(" - ")[0]
        elif mascota.isnumeric():
            microchip = mascota
        else:
            return JsonResponse({"mensaje" : {"Error":"El número de microchip no existe"}},status=400)

        mascota = Mascota.objects.filter(micro_chip=microchip).first()

        if not mascota:
            return JsonResponse({"mensaje" : {"Error":"El número de microchip no existe"}},status=400)

        request.POST._mutable = True
        request.POST['mascota'] = mascota.pk
        form = TurnoForm(request.POST, initial={'mascota': mascota})

        if not form.is_valid():
            return JsonResponse({"mensaje" : form.errors},status=400)

        form.save()

        return JsonResponse({},status=201)
    else:
        return JsonResponse({"mensaje":"Este método no está permitido"},status=403)


@login_required
@permission_required('turnos.view_turno',raise_exception=True)
def obtener_turnos(request):
    if request.method == 'GET':
        turnos = Turno.objects.all()
        print(request.user.tipo_usuario)
        if request.user.tipo_usuario == 'propietario':
            turnos = turnos.filter(mascota__duenio=request.user)
        turnos_json = []
        for turno in turnos:
            turnos_json.append({
                'id': turno.pk,
                'mascota': turno.mascota.nombre,
                'title': turno.descripcion_corta,
                'descripcion': turno.descripcion,
                'tipo_turno': turno.tipo_turno,
                'start': turno.inicio.strftime("%Y-%m-%dT%H:%M:%S"),
                'end': turno.fin.strftime("%Y-%m-%dT%H:%M:%S")
            })
        return JsonResponse(turnos_json,status=200,safe=False)
    else:
        return JsonResponse({"mensaje":"Este método no está permitido"},status=403)


@login_required
@permission_required('turnos.delete_turno',raise_exception=True)
def borrar_turno(request):
    if request.method == 'POST':
        id_turno = request.POST.get('id_turno')
        print(id_turno)
        turno = Turno.objects.filter(pk=id_turno).first()
        if turno:
            turno.delete()
            return JsonResponse({},status=200)
        else:
            return JsonResponse({"mensaje" : {"Error":"El turno no existe"}},status=400)
    else:
        return JsonResponse({"mensaje":"Este método no está permitido"},status=403)

osneal/templates/usuarios/alta-propietarios.html
{% extends 'dash-base.html' %}
    <!-- COMIENZA CONTENIDO DEL MENU -->
    
    {% block contenido %}
      
    <div class="text">ALTA DE PROPIETARIOS</div>

    <div class="container">
     <form>
       <div class="form-group">
         <label for="nombre">Nombre:</label>
         <input type="text" id="nombre" name="nombre" required>
       </div>

       <div class="form-group">
         <label for="dni">DNI:</label>
         <input type="text" id="dni" name="dni" required>
       </div>

       <div class="form-group">
         <label for="fecha-nacimiento">Fecha de nacimiento:</label>
         <input type="date" id="fecha-nacimiento" name="fecha-nacimiento" required>
       </div>

       <div class="form-group">
         <label for="direccion">Dirección:</label>
         <input type="text" id="direccion" name="direccion" required>
       </div>

       <div class="form-group">
         <label for="provincia">Provincia:</label>
         <input type="text" id="provincia" name="provincia" required>
       </div>

       <div class="form-group">
         <label for="localidad">Localidad:</label>
         <input type="text" id="localidad" name="localidad" required>
       </div>

       <div class="form-group">
         <label for="celular">Celular:</label>
         <input type="tel" id="celular" name="celular" required>
       </div>

       <div class="btn-container">
         <button type="submit">CARGAR</button>
         <button type="button">MODIFICAR</button>
         <button type="button">ELIMINAR</button>
       </div>
     </form>
   </div>
    {% endblock contenido %}
      
    

osneal/templates/usuarios/carga_usuarios_admin.html
{% extends 'dash-base.html' %}
<!-- COMIENZA CONTENIDO DEL MENU -->

{% block contenido %}

<div class="text">GESTION DE USUARIOS - OSNeal  </div>


{% include 'includes/mensajes.html' %}
  

<div class="text">BUSQUEDA DE USUARIOS</div>
<form class="form-inline" id="search-form" method="GET" action="{% url 'usuarios:buscar_usuario' %}">
  <div class="form-group mb-2">
    <label for="search-dni" class="sr-only">DNI</label>
    <input name="dni_usuario" type="text" class="form-control" id="search-dni"
      placeholder="Ingrese el DNI del Usuario que desea MODIFICAR o ELIMINAR">
  </div>
  <button type="submit" class="btn btn-primary mb-2">Buscar</button>
</form>

<div class="text">CARGA DE NUEVOS USUARIOS</div>
<form method="POST" action="{% url 'usuarios:crear_usuario' %}">
  {% csrf_token %}
  {% include 'includes/formulario.html' %}
  <div class="form-group">
    <button type="submit" class="btn btn-primary mx-xxl-5">Cargar</button>
  </div>
</form>

{% endblock contenido %}

osneal/templates/usuarios/editar_usuario_admin.html
{% extends 'dash-base.html' %}
<!-- COMIENZA CONTENIDO DEL MENU -->

{% block contenido %}

<div class="text">EDITANDO USUARIO {{object.nombre}} {{object.apellido}} </div>



<form method="POST" action="{% url 'usuarios:editar_usuario' object.pk %}">
  {% csrf_token %}
  {% include 'includes/formulario.html' %}
  <div class="form-group">
    <button type="submit" class="btn btn-secondary mx-5">Modificar</button>
  </div>

</form>
</div>
{% endblock contenido %}

osneal/templates/usuarios/login.html
{% load static %}

<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<!------ Include the above in your HEAD tag ---------->

<!DOCTYPE html>
<html>

<head>
	<title>OSNeal - Ingreso de USUARIOS</title>

	<!--Bootsrap 4 CDN-->
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
		integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

	<!--Fontawesome CDN-->
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css"
		integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">

	<!--Custom styles-->
	<link rel="stylesheet" type="text/css" href="{% static 'css/estilos_login.css' %}">
</head>

<body>
	<div class="container">
		<div class="d-flex justify-content-center h-100">
			<div class="card">
				<div class="card-header">
					<h3>INGRESO DE USUARIOS</h3>

				</div>
				<div class="card-body">
					<form method="POST" action="{% url 'usuarios:login' %}">
						{% csrf_token %}
						{% if form.errors %}
						<div class="alert alert-danger">
							{{ form.non_field_errors }}
							{% if form.username.errors %}
							<span>Nombre de usuario:</span>
							{{ form.username.errors }}
							{% endif %}
							{% if form.password.errors %}
							<span>Contraseña:</span>
							{{ form.password.errors }}
							{% endif %}
						</div>

						{% endif %}


						<div class="input-group form-group">
							<div class="input-group-prepend">
								<span class="input-group-text"><i class="fas fa-user"></i></span>
							</div>
							<input type="text" class="form-control" name="username"
								placeholder="Ingrese su correo electronico">

						</div>
						<div class="input-group form-group">
							<div class="input-group-prepend">
								<span class="input-group-text"><i class="fas fa-key"></i></span>
							</div>
							<input type="password" name="password" class="form-control"
								placeholder="Ingrese su contraseña">
						</div>
						<div class="row align-items-center remember">
							<input type="checkbox">Recordarme
						</div>
						<div class="form-group">
							<input type="submit" value="INGRESAR" class="btn float-right login_btn">
						</div>
					</form>
				</div>
				<div class="card-footer">
					<div class="d-flex justify-content-center">
						<a href="#">¿Olvidaste tu contraseña?</a>
					</div>
				</div>
			</div>
		</div>
	</div>
</body>

<footer class="footer">
	<div class="container-footer">
		<div class="row">
			<div class="col-lg-6">
				<button type="button" href="#" class="btn btn-primary btn-lg">¡Nuestros Planes! - DESCARGA EL CATALOGO</button>
			</div>
		</div>
	</div>
</footer>

</html>

osneal/templates/usuarios/resultado_busqueda_usuarios.html
{% extends 'dash-base.html' %}
<!-- COMIENZA CONTENIDO DEL MENU -->

{% block contenido %}

<nav class="navbar navbar-dark bg-dark">
  <a class="navbar-brand" href="{% url 'usuarios:crear_usuario' %}">Volver</a>
</nav>
<div class="container my-4">
  <h1 class="text-center">Resultados de búsqueda</h1>
  <div class="table-responsive">
    <table class="table table-striped">
      <thead>
        <tr>
          <th>Nombre</th>
          <th>DNI</th>
          <th>Correo electrónico</th>
          <th>Especialidad</th>
          <th>Fecha de nacimiento</th>
          <th>Dirección</th>
          <th>Provincia</th>
          <th>Localidad</th>
          <th>Celular</th>
          <th>Editar</th>
          <th>Eliminar</th>
        </tr>
      </thead>
      <tbody>
        {% for usuario in usuarios %}
        <tr>
          <td>{{usuario.nombre}} {{usuario.apellido}}</td>
          <td>{{usuario.dni}}</td>
          <td>{{usuario.email}}</td>
          <td>Especialidad</th>
          <td>{{usuario.fecha_nacimiento}}</td>
          <td>{{usuario.direccion}}</td>
          <td>{{usuario.provincia}}</td>
          <td>{{usuario.localidad}}</td>
          <td>{{usuario.telefono}}</td>
          <td><a href="{% url 'usuarios:editar_usuario' usuario.pk %}" class="btn btn-primary">Editar</a></td>
          <td><a class="btn btn-danger" href="{% url 'usuarios:borrar_usuario' usuario.pk %}" data-confirm="¿Realmente quieres borrar el usuario?">
            Eliminar
          </a></td>
          {% endfor %}
      </tbody>
    </table>
  </div>

  {% endblock contenido %}

  {% block js %}
  <script>
    new jBox('Confirm', {
      confirmButton: 'Eliminar',
      cancelButton: 'No'
    });
 
  </script>
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
  {% endblock js %}