osneal/mascotas/urls.py
from django.urls import path,re_path
from django.views.generic import TemplateView
from .views import (
    CrearMascota,
    BorrarMascota,
    ModificarMascota,
    BuscarMascota,
    CrearHistorial,
    EditarHistorialView,
    ListarHistorialesView,
    BorrarHistorialVew,
    CrearVacunaView,
    MascotasAutocomplete,
    MascotasByDniAutocomplete,
    ListarVacunasView,
    EditarVacunaView,
    BorrarVacunaView,

    #Vistas para usuarios propietarios
    MisMascotasView,
    VacunasMisMascotasView,
    HistorialesMisMascotasView,

    )

app_name = 'mascotas'

urlpatterns = [
    # MASCOTAS ADMIN
    path('carga/', CrearMascota.as_view(),name='carga'),
    path('<int:pk>/borrar/', BorrarMascota.as_view(),name='borrar'),
    path('<int:pk>/modificar/', ModificarMascota.as_view(),name='modificar'),
    path('buscar/', BuscarMascota.as_view(),name='buscar'),

    # HISTORIALES ADMIN
    path('carga_historial/', CrearHistorial.as_view(),name='carga_historial'),
    path('<int:pk>/editar_historial/', EditarHistorialView.as_view(),name='editar_historial'),
    path('<int:pk>/listado_historiales/', ListarHistorialesView.as_view(),name='listado_historiales'),
    path('<int:pk>/borrar_historial/', BorrarHistorialVew.as_view(),name='borrar_historial'),

    # VACUNAS ADMIN
    path('carga_vacuna/', CrearVacunaView.as_view(),name='carga_vacuna'),
    path('<int:pk>/listado_vacunas/', ListarVacunasView.as_view(),name='listado_vacunas'),
    path('<int:pk>/editar_vacuna/', EditarVacunaView.as_view(),name='editar_vacuna'),
    path('<int:pk>/borrar_vacuna/', BorrarVacunaView.as_view(),name='borrar_vacuna'),

    #URLS PARA USUARIOS COMUNES
    path('mis_mascotas/',MisMascotasView.as_view(),name='mis_mascotas'),
    path('mis_mascotas/<int:pk>/vacunas',VacunasMisMascotasView.as_view(),name='mis_mascotas_vacunas'),
    path('mis_mascotas/<int:pk>/historial',HistorialesMisMascotasView.as_view(),name='mis_mascotas_historial'),

    # AUTOCOMPLETE
    re_path(
        r'^mascotas-autocomplete/$',
        MascotasAutocomplete.as_view(),
        name='mascotas-autocomplete',
    ),
    re_path(
        r'^mascotas-by-dni-autocomplete/$',
        MascotasByDniAutocomplete.as_view(),
        name='mascotas-by-dni-autocomplete',
    ),

    ]

osneal/turnos/urls.py
from django.urls import path
from django.views.generic import TemplateView
from .views import (
    crear_turno,
    obtener_turnos,
    borrar_turno,
    )


app_name='turnos'

urlpatterns = [
    path('turnos_admin/', TemplateView.as_view(template_name='turnos/admin/turnos_admin.html'),name='turnos_admin'),
    path('crear_turnos_admin/', crear_turno,name='crear_turnos_admin'),
    path('obtener_turnos_admin/', obtener_turnos,name='obtener_turnos_admin'),
    path('borrar_turnos_admin/', borrar_turno,name='borrar_turnos_admin'),
    path('turnos_usuario/', TemplateView.as_view(template_name='vista_usuarios/turnos_usuario.html'),name='turnos_usuario'),
]

osneal/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('mascotas/', include('mascotas.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATICFILES_DIRS[0])

users/urls.py
from django.contrib import admin
from django.urls import path
from .views import InicarSesion,CerrarSesion

app_name = 'users'

urlpatterns = [
    path('iniciar-sesion/',InicarSesion.as_view(),name='iniciar-sesion'),
    path('salir/',CerrarSesion.as_view(),name='salir'),
]

osneal/pagos/models.py
from django.db import models

# Create your models here.

osneal/turnos/forms.py
from django import forms
from .models import Turno
from mascotas.models import Mascota
from django.utils import timezone
from datetime import timedelta

class TurnoForm(forms.ModelForm):

    descripcion = forms.CharField(required=False)
    inicio = forms.DateTimeField(input_formats=["%Y-%m-%dT%H:%M"])
    fin = forms.DateTimeField(input_formats=["%Y-%m-%dT%H:%M"])

    class Meta:
        model = Turno
        fields = '__all__'


    def clean(self):
        cleaned_data = super().clean()
        inicio = self.cleaned_data['inicio']
        fin = self.cleaned_data['fin']

        if inicio > fin:
            raise forms.ValidationError("La fecha de inicio no puede mayor a la fecha de fin.")
        elif fin < inicio:
            raise forms.ValidationError("La fecha de fin no puede ser menor a la fecha de inicio.")

        return cleaned_data

    def clean_inicio(self):
        inicio = self.cleaned_data['inicio']
        # Ajustar la zona horaria restando 3 horas
        inicio -= timedelta(hours=3)
        return inicio

    def clean_fin(self):
        fin = self.cleaned_data['fin']
        # Ajustar la zona horaria restando 3 horas
        fin -= timedelta(hours=3)
        return fin

osneal/mascotas/views.py
from django.shortcuts import render,redirect
from django.views.generic import CreateView, DeleteView, UpdateView, ListView
from mascotas.forms import MascotaForm,HistorialForm,VacunaForm, EditarHistorialForm,EditarVacunaForm
from mascotas.models import Mascota,Vacuna,HistorialClinico
from usuarios.models import Usuario
from mascotas.tables import VacunaTable, HistorialTable,VacunaTablePropietario,HistorialTablePropietario
from django.urls import reverse_lazy
from dal import autocomplete
from django_tables2 import SingleTableView
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.contrib import messages




# MASCOTAS
class CrearMascota(PermissionRequiredMixin,SuccessMessageMixin,CreateView):
    '''Clase para crear mascotas'''
    template_name = 'mascotas/carga_admin.html'
    success_url = reverse_lazy('mascotas:carga')
    form_class = MascotaForm
    success_url = reverse_lazy('mascotas:carga')
    success_message = "Mascota creada correctamente"
    permission_required = 'mascotas.add_mascota'
    login_url = reverse_lazy('usuarios:login')




class BorrarMascota(PermissionRequiredMixin,DeleteView):
    queryset = Mascota.objects.all()
    success_url = reverse_lazy('mascotas:carga')
    template_name = 'mascotas/carga_admin.html'
    pk_url_kwarg = 'pk'
    permission_required = 'mascotas.delete_mascota'
    login_url = reverse_lazy('usuarios:login')
    success_message = "Mascota eliminada correctamente"


    def get(self, request, *args, **kwargs):
        self.delete(self, request, *args, **kwargs)
        messages.success(self.request, self.success_message)
        return redirect('mascotas:carga')


class ModificarMascota(PermissionRequiredMixin,SuccessMessageMixin,UpdateView):
    '''Clase para modificar mascotas'''
    model = Mascota
    template_name = 'mascotas/modificar.html'
    form_class = MascotaForm
    pk_url_kwarg = 'pk'
    permission_required = 'mascotas.change_mascota'
    login_url = reverse_lazy('usuarios:login')
    success_url = reverse_lazy('mascotas:carga')
    success_message = "Mascota modificada correctamente"



class BuscarMascota(PermissionRequiredMixin,ListView):
    '''Clase para buscar mascotas'''
    model = Mascota
    template_name = 'mascotas/resultado_busqueda_mascotas.html'
    context_object_name = 'mascotas'
    permission_required = 'mascotas.view_mascota'
    login_url = reverse_lazy('usuarios:login')


    def get_queryset(self):
        '''Metodo para buscar mascotas'''
        queryset = super().get_queryset()
        busqueda = self.request.GET.get('mirco_chip',None)
        if busqueda:
            return queryset.filter(micro_chip__contains=busqueda)
        else:
            return queryset



class MascotasAutocomplete(PermissionRequiredMixin,autocomplete.Select2QuerySetView):
    '''Clase para autocompletar mascotas'''
    permission_required = 'mascotas.add_mascota'
    login_url = reverse_lazy('usuarios:login')

    def get_queryset(self):
        if not self.request.user.is_authenticated:
            return Mascota.objects.none()

        qs = Mascota.objects.all()

        if self.q:
            qs = qs.filter(micro_chip__istartswith=self.q)

        return qs


class MascotasByDniAutocomplete(PermissionRequiredMixin,autocomplete.Select2QuerySetView):
    '''Clase para autocompletar mascotas por dni'''
    permission_required = 'mascotas.add_mascota'
    login_url = reverse_lazy('usuarios:login')

    def get_queryset(self):
        if not self.request.user.is_authenticated:
            return Mascota.objects.none()

        qs = Mascota.objects.all()

        if self.q:
            qs = qs.filter(duenio__dni=self.q)

        return qs

# HISTORIAL

class CrearHistorial(PermissionRequiredMixin,SuccessMessageMixin,CreateView):
    '''Clase para crear historiales'''
    template_name = 'mascotas/historial_medico_admin.html'
    success_url = reverse_lazy('mascotas:carga_historial')
    form_class = HistorialForm
    permission_required = 'mascotas.add_historialclinico'
    login_url = reverse_lazy('usuarios:login')
    success_message = "Historial creado correctamente"

class BorrarHistorialVew(PermissionRequiredMixin,SuccessMessageMixin,DeleteView):
    '''Clase para eliminar historiales'''
    model = HistorialClinico
    pk_url_kwarg = 'pk'
    success_url = reverse_lazy('mascotas:buscar')
    success_message = "Historial eliminado correctamente"
    template_name = 'mascotas/carga_admin.html'
    permission_required = 'mascotas.delete_historialclinico'
    login_url = reverse_lazy('usuarios:login')

    def get(self, request, *args, **kwargs):
        self.delete(self, request, *args, **kwargs)
        messages.success(self.request, self.success_message)
        return redirect('mascotas:carga')


class EditarHistorialView(PermissionRequiredMixin,SuccessMessageMixin,UpdateView):
    '''Clase para modificar historiales'''
    model = HistorialClinico
    template_name = 'mascotas/historial_medico_admin.html'
    form_class = EditarHistorialForm
    pk_url_kwarg = 'pk'
    success_message = "Historial modificado correctamente"
    permission_required = 'mascotas.change_historialclinico'
    login_url = reverse_lazy('usuarios:login')
    success_url = reverse_lazy('mascotas:carga')

class ListarHistorialesView(PermissionRequiredMixin,SingleTableView):
    '''Clase para listar historiales de una mascota'''
    model = HistorialClinico
    template_name = 'mascotas/listado_historiales.html'
    table_class = HistorialTable
    permission_required = 'mascotas.change_historialclinico'
    login_url = reverse_lazy('usuarios:login')

    def get_queryset(self):
        '''Metodo para buscar mascotas'''
        queryset = super().get_queryset()
        busqueda = self.kwargs.get('pk',None)
        if busqueda:
            return queryset.filter(mascota__id=busqueda)
        else:
            return queryset



# VACUNAS
class CrearVacunaView(PermissionRequiredMixin,SuccessMessageMixin,CreateView):
    '''Clase para crear vacunas'''
    template_name = 'mascotas/vacunas_admin.html'
    success_url = reverse_lazy('mascotas:carga')
    form_class = VacunaForm
    permission_required = 'mascotas.add_vacuna'
    login_url = reverse_lazy('usuarios:login')
    success_message = "Vacuna cargada correctamente"

class ListarVacunasView(PermissionRequiredMixin,SingleTableView):
    '''Clase para listar vacunas de una mascota'''
    model = Vacuna
    template_name = 'mascotas/listado_vacunas.html'
    context_object_name = 'vacunas'
    table_class = VacunaTable
    permission_required = 'mascotas.view_vacuna'
    login_url = reverse_lazy('usuarios:login')

    def get_queryset(self):
        '''Metodo para buscar mascotas'''
        queryset = super().get_queryset()
        busqueda = self.kwargs.get('pk')
        print(busqueda)
        if busqueda:
            return queryset.filter(mascota=busqueda)
        else:
            return queryset


class EditarVacunaView(PermissionRequiredMixin,SuccessMessageMixin,UpdateView):
    '''Clase para listar vacunas de una mascota'''
    model = Vacuna
    template_name = 'mascotas/vacunas_admin.html'
    form_class = EditarVacunaForm
    pk_url_kwarg = 'pk'
    permission_required = 'mascotas.change_vacuna'
    login_url = reverse_lazy('usuarios:login')
    success_url = reverse_lazy('mascotas:carga')
    success_message = "Vacuna modificada correctamente"


class BorrarVacunaView(PermissionRequiredMixin,SuccessMessageMixin,DeleteView):
    '''Clase para eliminar vacunas de una mascota'''
    model = Vacuna
    pk_url_kwarg = 'pk'
    success_message = "Vacuna eliminada correctamente"
    success_url = reverse_lazy('mascotas:carga')
    template_name = 'mascotas/vacunas_admin.html'
    permission_required = 'mascotas.delete_mascota'
    login_url = reverse_lazy('usuarios:login')

    def get(self, request, *args, **kwargs):
        self.delete(self, request, *args, **kwargs)
        messages.success(self.request, self.success_message)
        return redirect('mascotas:carga')


class MisMascotasView(PermissionRequiredMixin,ListView):
    '''Clase para listar las mascotas de un usuario'''
    model = Mascota
    template_name = 'vista_usuarios/mascotas_usuario.html'
    context_object_name = 'mascotas'
    permission_required = 'mascotas.view_mascota'
    login_url = reverse_lazy('usuarios:login')

    def get_queryset(self):
        '''Metodo para buscar mascotas'''
        queryset = super().get_queryset()
        busqueda = self.request.user
        if busqueda:
            return queryset.filter(duenio=busqueda)
        else:
            return queryset

class VacunasMisMascotasView(PermissionRequiredMixin,SingleTableView):
    '''Clase para listar las vacunas de las mascotas de un usuario'''
    model = Vacuna
    template_name = 'vista_usuarios/listado_vacunas.html'
    context_object_name = 'vacunas'
    permission_required = 'mascotas.view_vacuna'
    login_url = reverse_lazy('usuarios:login')
    table_class = VacunaTablePropietario

    def get_queryset(self):
        pk = self.kwargs.get('pk')
        queryset = super().get_queryset()
        queryset = queryset.filter(mascota__duenio=self.request.user).filter(mascota__id=pk)

        return queryset


class HistorialesMisMascotasView(PermissionRequiredMixin,SingleTableView):
    '''Clase para listar los historiales de las mascotas de un usuario'''
    model = HistorialClinico
    template_name = 'vista_usuarios/historial_usuario.html'
    permission_required = 'mascotas.view_historialclinico'
    login_url = reverse_lazy('usuarios:login')
    table_class = HistorialTablePropietario

    def get_queryset(self,**kwargs):
        queryset = super().get_queryset()
        queryset = queryset.filter(mascota__duenio=self.request.user).filter(mascota__id=self.kwargs.get('pk'))
        return queryset

osneal/pagos/views.py
from django.shortcuts import render

# Create your views here.

osneal/turnos/views.py
from django.shortcuts import render
from django.http import JsonResponse
from .models import Turno
from .forms import TurnoForm
from mascotas.models import Mascota
from django.contrib.auth.decorators import login_required, permission_required

@login_required
@permission_required('turnos.add_turno',raise_exception=True)
def crear_turno(request):
    if request.method == 'POST':

        mascota = request.POST.get('mascota')

        if not mascota.find(" - ") == -1:
            microchip = mascota.split(" - ")[0]
        elif mascota.isnumeric():
            microchip = mascota
        else:
            return JsonResponse({"mensaje" : {"Error":"El número de microchip no existe"}},status=400)

        mascota = Mascota.objects.filter(micro_chip=microchip).first()

        if not mascota:
            return JsonResponse({"mensaje" : {"Error":"El número de microchip no existe"}},status=400)

        request.POST._mutable = True
        request.POST['mascota'] = mascota.pk
        form = TurnoForm(request.POST, initial={'mascota': mascota})

        if not form.is_valid():
            return JsonResponse({"mensaje" : form.errors},status=400)

        form.save()

        return JsonResponse({},status=201)
    else:
        return JsonResponse({"mensaje":"Este método no está permitido"},status=403)


@login_required
@permission_required('turnos.view_turno',raise_exception=True)
def obtener_turnos(request):
    if request.method == 'GET':
        turnos = Turno.objects.all()
        print(request.user.tipo_usuario)
        if request.user.tipo_usuario == 'propietario':
            turnos = turnos.filter(mascota__duenio=request.user)
        turnos_json = []
        for turno in turnos:
            turnos_json.append({
                'id': turno.pk,
                'mascota': turno.mascota.nombre,
                'title': turno.descripcion_corta,
                'descripcion': turno.descripcion,
                'tipo_turno': turno.tipo_turno,
                'start': turno.inicio.strftime("%Y-%m-%dT%H:%M:%S"),
                'end': turno.fin.strftime("%Y-%m-%dT%H:%M:%S")
            })
        return JsonResponse(turnos_json,status=200,safe=False)
    else:
        return JsonResponse({"mensaje":"Este método no está permitido"},status=403)


@login_required
@permission_required('turnos.delete_turno',raise_exception=True)
def borrar_turno(request):
    if request.method == 'POST':
        id_turno = request.POST.get('id_turno')
        print(id_turno)
        turno = Turno.objects.filter(pk=id_turno).first()
        if turno:
            turno.delete()
            return JsonResponse({},status=200)
        else:
            return JsonResponse({"mensaje" : {"Error":"El turno no existe"}},status=400)
    else:
        return JsonResponse({"mensaje":"Este método no está permitido"},status=403)

osneal/templates/vista_usuarios/historial_usuario.html
{% extends 'dash-base.html' %}
{% load render_table from django_tables2 %}

    <!-- COMIENZA CONTENIDO DEL MENU -->

    {% block contenido %}

    <div class="container">
      <h1>Historial Clínico {{mascota.nombre}}</h1>
      {% render_table table %}

    </div>

  {% endblock contenido %}

  {% block js %}
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
  {% endblock js %}

osneal/templates/vista_usuarios/listado_vacunas.html
{% extends 'dash-base.html' %}
{% load render_table from django_tables2 %}
<!-- COMIENZA CONTENIDO DEL MENU -->

{% block contenido %}

<div class="text">Historial de Vacunas</div>

<div class="container">
  {% render_table table %}


{% endblock contenido %}


{% block js %}
<script>

  {% include 'includes/confirm_jbox.js' %}
</script>
{% endblock js %}

osneal/templates/vista_usuarios/mascotas_usuario.html
{% extends 'dash-base.html' %}
{% load static %}
    <!-- COMIENZA CONTENIDO DEL MENU -->

    {% block contenido %}

    <div class="container">
      <h1>Mascotas</h1>


      <div class="row">
        {% for mascota in mascotas  %}
        <!-- Creamos una tarjeta para cada mascota -->
        <div class="col-md-4">
          <div class="card">

            {% if mascota.foto %}
            <img src="{{mascota.foto.url}}" class="card-img-top" alt="Imagen de la mascota">
            {% else %}
            <img src="{% static 'images/default_img.png' %}" class="card-img-top" alt="Imagen de la mascota">
            {% endif %}
            <div class="card-body">
              <h5 class="card-title">{{mascota.nombre}}</h5>
              <p class="card-text">Microchip: {{mascota.micro_chip}} </p>
              <!-- Agregamos los botones para acceder al historial clínico y las vacunas -->
              <a href="{% url 'mascotas:mis_mascotas_historial' mascota.pk %}" class="btn btn-primary">Historial Clínico</a>
              <a href="{% url 'mascotas:mis_mascotas_vacunas' mascota.pk  %}" class="btn btn-secondary">Vacunas</a>
            </div>
          </div>
        </div>
        {% endfor %}
    </div>


  {% endblock contenido %}

  {% block js %}
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
  {% endblock js %}

osneal/templates/vista_usuarios/turnos_usuario.html
{% extends 'dash-base.html' %}


{% block encabezado %}
<!-- fullcalendar -->

<script src='https://cdn.jsdelivr.net/npm/fullcalendar@6.1.5/index.global.min.js'></script>
<script src="https://code.jquery.com/ui/1.13.2/jquery-ui.js"
  integrity="sha256-xLD7nhI62fcsEZK2/v8LsBcb4lG7dgULkuXoXB/j91c=" crossorigin="anonymous"></script>
<style>
  .ui-autocomplete {
    z-index: 1050 !important;
    position: absolute;
    background-color: #fff;
    border: 1px solid #ccc;
    padding: 5px;
    max-height: 200px;
    overflow-y: auto;
  }

  .ui-autocomplete li {
    list-style: none;
    padding: 5px;
    cursor: pointer;
  }

  .ui-autocomplete li:hover {
    background-color: #f5f5f5;
  }

  #calendar {
    height: 90vh;
  }
</style>
{% endblock encabezado %}


{% block contenido %}
{% csrf_token %}


<div class="text">Turnos</div>
<div id='calendar'></div>

<div id="DetailModal" class="modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="myModalLabel">Detalle de Turno</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <div class="">
          <label for="detalle_descripcion_corta">Descripción corta del turno</label>
          <input type="text" id="detalle_descripcion_corta" name="detalle_descripcion_corta" class="form-control"
            readonly>
        </div>
        <div class="ui-widget">
          <label for="detalle_mascota">Nombre de la mascota:</label>
          <input type="text" id="detalle_mascota" name="detalle_mascota" class="form-control" readonly>

        </div>
        <div class="">
          <label for="detalle_tipo_turno">Tipo de turno</label>
          <input type="text" id="detalle_tipo_turno" name="detalle_tipo_turno" class="form-control" readonly>
        </div>
        <div class="">
          <label for="detalle_inicio">Fecha y Hora de inicio</label>
          <input type="datetime-local" id="detalle_inicio" name="detalle_inicio" class="form-control" readonly>
        </div>
        <div class="">
          <label for="detalle_fin">Fecha y Hora de fin</label>
          <input type="datetime-local" id="detalle_fin" name="detalle_fin" class="form-control" readonly>
        </div>
        <div class="">
          <label for="detalle_descripcion">Descripción</label>
          <textarea name="detalle_descripcion" id="detalle_descripcion" cols="30" rows="5" readonly></textarea>
        </div>
        <!-- Otros campos del formulario -->

      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cerrar</button>
      </div>
    </div>
  </div>
</div>


<script>

  $(document).ready(function () {

    const NOMBRES_CAMPO = {
      "descripcion_corta": "Descripción corta del turno",
      "mascota": "Microchip de mascota",
      "tipo_turno": "Tipo de turno",
      "inicio": "Fecha y Hora de inicio",
      "fin": "Fecha y Hora de fin",
      "descripcion": "Descripción",
      "Error": "Error",
      "__all__": "Error",
    }

    const cargar_eventos = () => {
      $.ajax({
        url: '/turnos/obtener_turnos_admin/',
        type: 'GET',
        dataType: 'json',
        success: function (response) {
          console.log(response)
          calendar.removeAllEvents();  // Eliminar todos los eventos actuales
          calendar.addEventSource(response);  // Agregar los nuevos eventos
          calendar.refetchEvents();  // Volver a cargar los eventos en el calendario
        },
        error: function (error) {
          console.error(error);
        }
      });
    }


    var calendarEl = document.getElementById('calendar');
    var calendar = new FullCalendar.Calendar(calendarEl, {
      locale: 'es',
      buttonText: {
        today: 'Hoy',
        month: 'Mes',
      },
      // selectable: true,
      headerToolbar: {
        left: 'prev,next today',
        center: 'title',
        right: 'dayGridMonth,',

      },
      eventClick: function (info) {
        console.log(info.event.id)
        inicio = info.event.startStr
        inicio = new Date(inicio)
        inicio.setHours(inicio.getHours() - 3)
        inicio = inicio.toISOString().slice(0, 16);
        fin = info.event.endStr
        fin = new Date(fin)
        fin.setHours(fin.getHours() - 3)
        fin = fin.toISOString().slice(0, 16);

        $('#DetailModal').modal('show') // initializes and invokes show immediately
        $('#detalle_descripcion_corta').val(info.event.title)
        $('#detalle_mascota').val(info.event.extendedProps.mascota)
        $('#detalle_tipo_turno').val(info.event.extendedProps.tipo_turno)
        console.log(info.event.startStr)
        $('#detalle_inicio').val(inicio)
        $('#detalle_fin').val(fin)
        $('#detalle_descripcion').val(info.event.extendedProps.descripcion)

      }

    });
    calendar.render();
    cargar_eventos();





  });

</script>

{% endblock contenido %}

osneal/templates/vista_usuarios/vacunas_usuario.html
{% extends 'dash-base.html' %}
    <!-- COMIENZA CONTENIDO DEL MENU -->
    
    {% block contenido %}

    <div class="text">Historial de Vacunas</div>

    <div class="container">
      <h1>Vacunación de mascotas</h1>
      <table class="table">
        <thead>
          <tr>
            <th>Vacuna</th>
            <th>Fecha última vacunación</th>
            <th>Próxima vacunación</th>
                 <!-- VISUALIZACION SOLO PARA EL ADMIN -->
            <th>Editar</th>
            <th>Eliminar</th>
          </tr>
        </thead>
        <tbody id="tabla-vacunas">
          <tr>
            <td>Vacuna 1</td>
            <td>01/01/2022</td>
            <td>01/07/2022</td>
                <!-- VISUALIZACION SOLO PARA EL ADMIN -->
            <td><button class="btn btn-primary">Editar</button></td>
            <td><button class="btn btn-danger">Eliminar</button></td>
          </tr>
          <tr>
            <td>Vacuna 2</td>
            <td>01/01/2022</td>
            <td>01/07/2022</td>
            <td><button class="btn btn-primary">Editar</button></td>
            <td><button class="btn btn-danger">Eliminar</button></td>
          </tr>
          <!-- Agregar más filas de la tabla según sea necesario -->
        </tbody>
      </table>
    </div>

  {% endblock contenido %}

  {% block js %}

  {% endblock js %}