mascotas/urls.py
from django.urls import path
from .views import ListadoMascotas,BorrarMascota,EditarMascota,CrearMascota

app_name = 'mascotas'

urlpatterns = [
    path('listado/',ListadoMascotas.as_view(),name='listado'),
    path('<int:pk>/borrar/',BorrarMascota.as_view(),name='borrar'),
    path('<int:pk>/editar/',EditarMascota.as_view(),name='editar'),
    path('crear/',CrearMascota.as_view(),name='crear'),
]

osneal/mascotas/urls.py
from django.urls import path,re_path
from django.views.generic import TemplateView
from .views import (
    CrearMascota,
    BorrarMascota,
    ModificarMascota,
    BuscarMascota,
    CrearHistorial,
    EditarHistorialView,
    ListarHistorialesView,
    BorrarHistorialVew,
    CrearVacunaView,
    MascotasAutocomplete,
    MascotasByDniAutocomplete,
    ListarVacunasView,
    EditarVacunaView,
    BorrarVacunaView,

    #Vistas para usuarios propietarios
    MisMascotasView,
    VacunasMisMascotasView,
    HistorialesMisMascotasView,

    )

app_name = 'mascotas'

urlpatterns = [
    # MASCOTAS ADMIN
    path('carga/', CrearMascota.as_view(),name='carga'),
    path('<int:pk>/borrar/', BorrarMascota.as_view(),name='borrar'),
    path('<int:pk>/modificar/', ModificarMascota.as_view(),name='modificar'),
    path('buscar/', BuscarMascota.as_view(),name='buscar'),

    # HISTORIALES ADMIN
    path('carga_historial/', CrearHistorial.as_view(),name='carga_historial'),
    path('<int:pk>/editar_historial/', EditarHistorialView.as_view(),name='editar_historial'),
    path('<int:pk>/listado_historiales/', ListarHistorialesView.as_view(),name='listado_historiales'),
    path('<int:pk>/borrar_historial/', BorrarHistorialVew.as_view(),name='borrar_historial'),

    # VACUNAS ADMIN
    path('carga_vacuna/', CrearVacunaView.as_view(),name='carga_vacuna'),
    path('<int:pk>/listado_vacunas/', ListarVacunasView.as_view(),name='listado_vacunas'),
    path('<int:pk>/editar_vacuna/', EditarVacunaView.as_view(),name='editar_vacuna'),
    path('<int:pk>/borrar_vacuna/', BorrarVacunaView.as_view(),name='borrar_vacuna'),

    #URLS PARA USUARIOS COMUNES
    path('mis_mascotas/',MisMascotasView.as_view(),name='mis_mascotas'),
    path('mis_mascotas/<int:pk>/vacunas',VacunasMisMascotasView.as_view(),name='mis_mascotas_vacunas'),
    path('mis_mascotas/<int:pk>/historial',HistorialesMisMascotasView.as_view(),name='mis_mascotas_historial'),

    # AUTOCOMPLETE
    re_path(
        r'^mascotas-autocomplete/$',
        MascotasAutocomplete.as_view(),
        name='mascotas-autocomplete',
    ),
    re_path(
        r'^mascotas-by-dni-autocomplete/$',
        MascotasByDniAutocomplete.as_view(),
        name='mascotas-by-dni-autocomplete',
    ),

    ]

osneal/turnos/urls.py
from django.urls import path
from django.views.generic import TemplateView
from .views import (
    crear_turno,
    obtener_turnos,
    borrar_turno,
    )


app_name='turnos'

urlpatterns = [
    path('turnos_admin/', TemplateView.as_view(template_name='turnos/admin/turnos_admin.html'),name='turnos_admin'),
    path('crear_turnos_admin/', crear_turno,name='crear_turnos_admin'),
    path('obtener_turnos_admin/', obtener_turnos,name='obtener_turnos_admin'),
    path('borrar_turnos_admin/', borrar_turno,name='borrar_turnos_admin'),
    path('turnos_usuario/', TemplateView.as_view(template_name='vista_usuarios/turnos_usuario.html'),name='turnos_usuario'),
]

osneal/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('mascotas/', include('mascotas.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATICFILES_DIRS[0])

users/urls.py
from django.contrib import admin
from django.urls import path
from .views import InicarSesion,CerrarSesion

app_name = 'users'

urlpatterns = [
    path('iniciar-sesion/',InicarSesion.as_view(),name='iniciar-sesion'),
    path('salir/',CerrarSesion.as_view(),name='salir'),
]

osneal/pagos/models.py
from django.db import models

# Create your models here.

osneal/turnos/models.py
from django.db import models
from mascotas.models import Mascota

# Create your models here.
class Turno(models.Model):
    TIPO_TURNO = (
        ('Veterinaria', 'Veterinaria'),
        ('Peluquería', 'Peluquería'),
    )
    mascota = models.ForeignKey(Mascota,on_delete=models.CASCADE)
    descripcion_corta = models.CharField(max_length=250)
    descripcion = models.TextField()
    tipo_turno = models.CharField(max_length=250,choices=TIPO_TURNO)
    inicio = models.DateTimeField()
    fin = models.DateTimeField()
    fecha_creacion = models.DateTimeField(auto_now_add=True)
    fecha_modificacion = models.DateTimeField(auto_now=True)

osneal/turnos/forms.py
from django import forms
from .models import Turno
from mascotas.models import Mascota
from django.utils import timezone
from datetime import timedelta

class TurnoForm(forms.ModelForm):

    descripcion = forms.CharField(required=False)
    inicio = forms.DateTimeField(input_formats=["%Y-%m-%dT%H:%M"])
    fin = forms.DateTimeField(input_formats=["%Y-%m-%dT%H:%M"])

    class Meta:
        model = Turno
        fields = '__all__'


    def clean(self):
        cleaned_data = super().clean()
        inicio = self.cleaned_data['inicio']
        fin = self.cleaned_data['fin']

        if inicio > fin:
            raise forms.ValidationError("La fecha de inicio no puede mayor a la fecha de fin.")
        elif fin < inicio:
            raise forms.ValidationError("La fecha de fin no puede ser menor a la fecha de inicio.")

        return cleaned_data

    def clean_inicio(self):
        inicio = self.cleaned_data['inicio']
        # Ajustar la zona horaria restando 3 horas
        inicio -= timedelta(hours=3)
        return inicio

    def clean_fin(self):
        fin = self.cleaned_data['fin']
        # Ajustar la zona horaria restando 3 horas
        fin -= timedelta(hours=3)
        return fin

mascotas/views.py
from django.urls import reverse_lazy
from django.views.generic import ListView,DeleteView,UpdateView,CreateView
from .models import Mascota,FormularioMascota
# Create your views here.


class ListadoMascotas(ListView):
    '''
    Lista las mascotas.
    Uso queryset para traer todos los objetos, pero se puede usar el modelo (model=Mascota)
    '''
    queryset = Mascota.objects.all() 
    context_object_name = 'mascotas'
    template_name = 'mascotas/listado.html'

class BorrarMascota(DeleteView):
    '''
    Borra una mascota que se pasa por url el pk.
    Uso queryset para traer todos los objetos, pero se puede usar el modelo (model=Mascota)
    '''
    queryset = Mascota.objects.all()
    success_url = reverse_lazy('mascotas:listado')

class EditarMascota(UpdateView):
    '''
    Edita una mascota que se pasa por url el pk.
    Aca uso el model en lugar del atributo queryset.
    '''
    model = Mascota
    success_url = reverse_lazy('mascotas:listado')
    context_object_name = 'mascota'
    template_name = 'mascotas/editar_mascota.html'
    form_class = FormularioMascota

class CrearMascota(CreateView):
    model = Mascota
    template_name = 'mascotas/crear_mascota.html'
    success_url = reverse_lazy('mascotas:listado')
    form_class = FormularioMascota

osneal/mascotas/views.py
from django.shortcuts import render,redirect
from django.views.generic import CreateView, DeleteView, UpdateView, ListView
from mascotas.forms import MascotaForm,HistorialForm,VacunaForm, EditarHistorialForm,EditarVacunaForm
from mascotas.models import Mascota,Vacuna,HistorialClinico
from usuarios.models import Usuario
from mascotas.tables import VacunaTable, HistorialTable,VacunaTablePropietario,HistorialTablePropietario
from django.urls import reverse_lazy
from dal import autocomplete
from django_tables2 import SingleTableView
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.contrib import messages




# MASCOTAS
class CrearMascota(PermissionRequiredMixin,SuccessMessageMixin,CreateView):
    '''Clase para crear mascotas'''
    template_name = 'mascotas/carga_admin.html'
    success_url = reverse_lazy('mascotas:carga')
    form_class = MascotaForm
    success_url = reverse_lazy('mascotas:carga')
    success_message = "Mascota creada correctamente"
    permission_required = 'mascotas.add_mascota'
    login_url = reverse_lazy('usuarios:login')




class BorrarMascota(PermissionRequiredMixin,DeleteView):
    queryset = Mascota.objects.all()
    success_url = reverse_lazy('mascotas:carga')
    template_name = 'mascotas/carga_admin.html'
    pk_url_kwarg = 'pk'
    permission_required = 'mascotas.delete_mascota'
    login_url = reverse_lazy('usuarios:login')
    success_message = "Mascota eliminada correctamente"


    def get(self, request, *args, **kwargs):
        self.delete(self, request, *args, **kwargs)
        messages.success(self.request, self.success_message)
        return redirect('mascotas:carga')


class ModificarMascota(PermissionRequiredMixin,SuccessMessageMixin,UpdateView):
    '''Clase para modificar mascotas'''
    model = Mascota
    template_name = 'mascotas/modificar.html'
    form_class = MascotaForm
    pk_url_kwarg = 'pk'
    permission_required = 'mascotas.change_mascota'
    login_url = reverse_lazy('usuarios:login')
    success_url = reverse_lazy('mascotas:carga')
    success_message = "Mascota modificada correctamente"



class BuscarMascota(PermissionRequiredMixin,ListView):
    '''Clase para buscar mascotas'''
    model = Mascota
    template_name = 'mascotas/resultado_busqueda_mascotas.html'
    context_object_name = 'mascotas'
    permission_required = 'mascotas.view_mascota'
    login_url = reverse_lazy('usuarios:login')


    def get_queryset(self):
        '''Metodo para buscar mascotas'''
        queryset = super().get_queryset()
        busqueda = self.request.GET.get('mirco_chip',None)
        if busqueda:
            return queryset.filter(micro_chip__contains=busqueda)
        else:
            return queryset



class MascotasAutocomplete(PermissionRequiredMixin,autocomplete.Select2QuerySetView):
    '''Clase para autocompletar mascotas'''
    permission_required = 'mascotas.add_mascota'
    login_url = reverse_lazy('usuarios:login')

    def get_queryset(self):
        if not self.request.user.is_authenticated:
            return Mascota.objects.none()

        qs = Mascota.objects.all()

        if self.q:
            qs = qs.filter(micro_chip__istartswith=self.q)

        return qs


class MascotasByDniAutocomplete(PermissionRequiredMixin,autocomplete.Select2QuerySetView):
    '''Clase para autocompletar mascotas por dni'''
    permission_required = 'mascotas.add_mascota'
    login_url = reverse_lazy('usuarios:login')

    def get_queryset(self):
        if not self.request.user.is_authenticated:
            return Mascota.objects.none()

        qs = Mascota.objects.all()

        if self.q:
            qs = qs.filter(duenio__dni=self.q)

        return qs

# HISTORIAL

class CrearHistorial(PermissionRequiredMixin,SuccessMessageMixin,CreateView):
    '''Clase para crear historiales'''
    template_name = 'mascotas/historial_medico_admin.html'
    success_url = reverse_lazy('mascotas:carga_historial')
    form_class = HistorialForm
    permission_required = 'mascotas.add_historialclinico'
    login_url = reverse_lazy('usuarios:login')
    success_message = "Historial creado correctamente"

class BorrarHistorialVew(PermissionRequiredMixin,SuccessMessageMixin,DeleteView):
    '''Clase para eliminar historiales'''
    model = HistorialClinico
    pk_url_kwarg = 'pk'
    success_url = reverse_lazy('mascotas:buscar')
    success_message = "Historial eliminado correctamente"
    template_name = 'mascotas/carga_admin.html'
    permission_required = 'mascotas.delete_historialclinico'
    login_url = reverse_lazy('usuarios:login')

    def get(self, request, *args, **kwargs):
        self.delete(self, request, *args, **kwargs)
        messages.success(self.request, self.success_message)
        return redirect('mascotas:carga')


class EditarHistorialView(PermissionRequiredMixin,SuccessMessageMixin,UpdateView):
    '''Clase para modificar historiales'''
    model = HistorialClinico
    template_name = 'mascotas/historial_medico_admin.html'
    form_class = EditarHistorialForm
    pk_url_kwarg = 'pk'
    success_message = "Historial modificado correctamente"
    permission_required = 'mascotas.change_historialclinico'
    login_url = reverse_lazy('usuarios:login')
    success_url = reverse_lazy('mascotas:carga')

class ListarHistorialesView(PermissionRequiredMixin,SingleTableView):
    '''Clase para listar historiales de una mascota'''
    model = HistorialClinico
    template_name = 'mascotas/listado_historiales.html'
    table_class = HistorialTable
    permission_required = 'mascotas.change_historialclinico'
    login_url = reverse_lazy('usuarios:login')

    def get_queryset(self):
        '''Metodo para buscar mascotas'''
        queryset = super().get_queryset()
        busqueda = self.kwargs.get('pk',None)
        if busqueda:
            return queryset.filter(mascota__id=busqueda)
        else:
            return queryset



# VACUNAS
class CrearVacunaView(PermissionRequiredMixin,SuccessMessageMixin,CreateView):
    '''Clase para crear vacunas'''
    template_name = 'mascotas/vacunas_admin.html'
    success_url = reverse_lazy('mascotas:carga')
    form_class = VacunaForm
    permission_required = 'mascotas.add_vacuna'
    login_url = reverse_lazy('usuarios:login')
    success_message = "Vacuna cargada correctamente"

class ListarVacunasView(PermissionRequiredMixin,SingleTableView):
    '''Clase para listar vacunas de una mascota'''
    model = Vacuna
    template_name = 'mascotas/listado_vacunas.html'
    context_object_name = 'vacunas'
    table_class = VacunaTable
    permission_required = 'mascotas.view_vacuna'
    login_url = reverse_lazy('usuarios:login')

    def get_queryset(self):
        '''Metodo para buscar mascotas'''
        queryset = super().get_queryset()
        busqueda = self.kwargs.get('pk')
        print(busqueda)
        if busqueda:
            return queryset.filter(mascota=busqueda)
        else:
            return queryset


class EditarVacunaView(PermissionRequiredMixin,SuccessMessageMixin,UpdateView):
    '''Clase para listar vacunas de una mascota'''
    model = Vacuna
    template_name = 'mascotas/vacunas_admin.html'
    form_class = EditarVacunaForm
    pk_url_kwarg = 'pk'
    permission_required = 'mascotas.change_vacuna'
    login_url = reverse_lazy('usuarios:login')
    success_url = reverse_lazy('mascotas:carga')
    success_message = "Vacuna modificada correctamente"


class BorrarVacunaView(PermissionRequiredMixin,SuccessMessageMixin,DeleteView):
    '''Clase para eliminar vacunas de una mascota'''
    model = Vacuna
    pk_url_kwarg = 'pk'
    success_message = "Vacuna eliminada correctamente"
    success_url = reverse_lazy('mascotas:carga')
    template_name = 'mascotas/vacunas_admin.html'
    permission_required = 'mascotas.delete_mascota'
    login_url = reverse_lazy('usuarios:login')

    def get(self, request, *args, **kwargs):
        self.delete(self, request, *args, **kwargs)
        messages.success(self.request, self.success_message)
        return redirect('mascotas:carga')


class MisMascotasView(PermissionRequiredMixin,ListView):
    '''Clase para listar las mascotas de un usuario'''
    model = Mascota
    template_name = 'vista_usuarios/mascotas_usuario.html'
    context_object_name = 'mascotas'
    permission_required = 'mascotas.view_mascota'
    login_url = reverse_lazy('usuarios:login')

    def get_queryset(self):
        '''Metodo para buscar mascotas'''
        queryset = super().get_queryset()
        busqueda = self.request.user
        if busqueda:
            return queryset.filter(duenio=busqueda)
        else:
            return queryset

class VacunasMisMascotasView(PermissionRequiredMixin,SingleTableView):
    '''Clase para listar las vacunas de las mascotas de un usuario'''
    model = Vacuna
    template_name = 'vista_usuarios/listado_vacunas.html'
    context_object_name = 'vacunas'
    permission_required = 'mascotas.view_vacuna'
    login_url = reverse_lazy('usuarios:login')
    table_class = VacunaTablePropietario

    def get_queryset(self):
        pk = self.kwargs.get('pk')
        queryset = super().get_queryset()
        queryset = queryset.filter(mascota__duenio=self.request.user).filter(mascota__id=pk)

        return queryset


class HistorialesMisMascotasView(PermissionRequiredMixin,SingleTableView):
    '''Clase para listar los historiales de las mascotas de un usuario'''
    model = HistorialClinico
    template_name = 'vista_usuarios/historial_usuario.html'
    permission_required = 'mascotas.view_historialclinico'
    login_url = reverse_lazy('usuarios:login')
    table_class = HistorialTablePropietario

    def get_queryset(self,**kwargs):
        queryset = super().get_queryset()
        queryset = queryset.filter(mascota__duenio=self.request.user).filter(mascota__id=self.kwargs.get('pk'))
        return queryset

osneal/pagos/views.py
from django.shortcuts import render

# Create your views here.

osneal/templates/mascotas/carga_admin.html
{% extends 'dash-base.html' %}
<!-- COMIENZA CONTENIDO DEL MENU -->
{% load static %}

{% block encabezado %}
<style>
  body {

    background-color: #eee;
  }

  .card {

    background-color: #fff;
    padding: 15px;
    border: none;
  }

  /* .input-box {
    position: relative;
  }

  .input-box i {
    position: absolute;
    right: 13px;
    top: 15px;
    color: #ced4da;

  } */

  /* .form-control {

    height: 50px;
    background-color: #eeeeee69;
  } */

  /* .form-control:focus {
    background-color: #eeeeee69;
    box-shadow: none;
    border-color: #eee;
  } */


  .list {

    padding-top: 20px;
    padding-bottom: 10px;
    display: flex;
    align-items: center;

  }

  .border-bottom {

    border-bottom: 2px solid #eee;
  }

  .list i {
    font-size: 19px;
    color: red;
  }

  .list small {

    color: grey;
  }
</style>
{% endblock encabezado %}


{% block contenido %}

<div class="text">GESTION DE MASCOTAS - OSNeAl</div>

<div class="text">BUSCADOR DE MASCOTAS</div>

  <div class="input-group mb-3">
    <form action="{% url 'mascotas:buscar' %}" method="GET">
      <input type="text" name="mirco_chip" class="form-control" placeholder="Ingrese el Microchip de la mascota">
      <div class="input-group-append">
        <button class="btn btn-primary" type="submit">Buscar</button>
      </div>
    </form>
  </div>



<div class="text">CARGA DE MASCOTAS A PROPIETARIOS</div>
{% include 'includes/mensajes.html' %}


<form method="POST"  enctype="multipart/form-data">
  {% csrf_token %}
  {% include 'includes/formulario.html' %}

  <button type="submit" class="btn btn-primary">Agregar mascota</button>
</form>


{% endblock contenido %}


{% block js %}
{% endblock js %}

osneal/templates/mascotas/historial_medico_admin.html
{% extends 'dash-base.html' %}
<!-- COMIENZA CONTENIDO DEL MENU -->

{% block contenido %}

<div class="text">CARGA DE HISTORIALES CLINICOS</div>
{% include 'includes/mensajes.html' %}

<form method="POST">
  {% csrf_token %}
  {% include 'includes/formulario.html' %}


  <button type="submit" class="btn btn-primary">Guardar</button>
</form>
</div>



{% endblock contenido %}

osneal/templates/mascotas/listado_historiales.html
{% extends 'dash-base.html' %}
{% load render_table from django_tables2 %}
<!-- COMIENZA CONTENIDO DEL MENU -->

{% block contenido %}

<div class="text">Listado de Historiales clínicos</div>

<div class="container">
  {% render_table table %}
  
{% endblock contenido %}

{% block js %}
<script>

  {% include 'includes/confirm_jbox.js' %}
</script>
{% endblock js %}

osneal/templates/mascotas/modificar.html
{% extends 'dash-base.html' %}
<!-- COMIENZA CONTENIDO DEL MENU -->
{% load static %}

{% block encabezado %}
<style>
  body {

    background-color: #eee;
  }

  .card {

    background-color: #fff;
    padding: 15px;
    border: none;
  }



  .list {

    padding-top: 20px;
    padding-bottom: 10px;
    display: flex;
    align-items: center;

  }

  .border-bottom {

    border-bottom: 2px solid #eee;
  }

  .list i {
    font-size: 19px;
    color: red;
  }

  .list small {

    color: grey;
  }
</style>
{% endblock encabezado %}


{% block contenido %}

<div class="text">MODIFICACION DE {{object.nombre|upper}}</div>


<form method="POST" enctype="multipart/form-data" >
  {% csrf_token %}
  {% include 'includes/mensajes.html' %}
  {% include 'includes/formulario.html' %}
  <button type="submit" class="btn btn-primary">Modificar mascota</button>
</form>


{% endblock contenido %}


{% block js %}
{% endblock js %}

osneal/templates/mascotas/resultado_busqueda_mascotas.html
{% extends 'dash-base.html' %}
<!-- COMIENZA CONTENIDO DEL MENU -->

{% block contenido %}

<nav class="navbar navbar-dark bg-dark">
  <a class="navbar-brand" href="{% url 'mascotas:carga' %}">Volver</a>
</nav>
<div class="container my-4">
  <h1 class="text-center">Resultados de búsqueda</h1>
  <div class="table-responsive">
    <table class="table table-striped">
      <thead>
        <tr>
          <th>Nombre</th>
          <th>Microchip</th>
          <th>Especie</th>
          <th>Raza</th>
          <th>Pelaje</th>
          <th>Edad</th>
          <th>OSNeal Plan</th>
          <th>Vacunas</th>
          <th>Hist. Clinico</th>
          <th>Editar</th>
          <th>Eliminar</th>
        </tr>
      </thead>
      <tbody>
        {% for mascota in mascotas %}
        <tr>
          <td>{{mascota.nombre}}</td>
          <td>{{mascota.micro_chip}}</td>
          <td>{{mascota.especie}}</td>
          <td>{{mascota.raza}}</td>
          <td>{{mascota.pelaje}}</td>
          <td>{{mascota.edad}}</td>
          <td>{{mascota.tipo_plan}}</td>
          <td><a href="{% url 'mascotas:listado_vacunas' mascota.pk %}" class="btn btn-primary">Ver/Administrar</a></td>
          <td><a href="{% url 'mascotas:listado_historiales' mascota.pk %}" class="btn btn-primary">Ver/Gestionar</a></td>
          <td><a href="{% url 'mascotas:modificar' mascota.pk %}" class="btn btn-primary">Editar</a></td>
          <td><a class="btn btn-danger" href="{% url 'mascotas:borrar' mascota.pk %}" data-confirm="¿Realmente quieres borrar el usuario?">
            Eliminar
          </a></td>
          {% endfor %}
      </tbody>
    </table>
  </div>

  {% endblock contenido %}

  {% block js %}
  <script>
    new jBox('Confirm', {
      confirmButton: 'Eliminar',
      cancelButton: 'No'
    });
 
  </script>
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
  {% endblock js %}

osneal/templates/mascotas/vacunas_admin.html
{% extends 'dash-base.html' %}
<!-- COMIENZA CONTENIDO DEL MENU -->

{% block contenido %}

<div class="text">Vacunas</div>

{% include 'includes/mensajes.html' %}

<div class="container mt-4">
  <h1 class="mb-4">Vacunación de animales</h1>

  <form method="POST">
    {% csrf_token %}
    {% include 'includes/formulario.html' %}

    <button class="btn btn-primary mt-4" type="submit">Aplicar vacuna</button>
  </form>




  {% endblock contenido %}